### ISSUE TITLE
More Info About the Library

### ISSUE THREAD

**Issue by Sinansi** [dshipman/pyms#3]
Hello,

I dont understand what exactly this library can do.
Can I use this library to read real time intraday data from MetaStock to Python?

Thank you!

**Comment by GRZLTN** [comment]
The library reads MetaStock format data. If your MS data is real time I think it would be fair to assume you can read real time data. You may have issues if the operations happen concurrently as the MS updater can lock with the python if they run concurrently. I run a job that completes intraday updates on MS data and immediately after pushes this into a DB for processing. Rinse & repeat. Hope that helped.

**Comment by dshipman** [comment]
The library is built with daily data in mind, so would require some modification to work with intraday.  As mentioned by GRZLTN, it is built for 'Metastock - the data format', rather than offerings by 'Metastock - the company', or integration with 'Metastock - the application'.  You would have to contact them to find out what data format their Realtime product used;  it might be completely unrelated to the old Metastock format.

**Comment by dshipman** [comment]
Have added a brief explanation in the README
